shellEmulator: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3

packages:
  - 'apps/*'
  - 'packages/*'
  - 'mods/*'

allowBuilds:
  tree-sitter: true
  tree-sitter-gdscript: true
  tree-sitter-godot-resource: true
  vue-demi: false
